// <auto-generated />
namespace Casgem_CodefirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_final : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_final));
        
        string IMigrationMetadata.Id
        {
            get { return "202307171923352_mig_final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
